import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'frusan-planification-table',
  templateUrl: './planification-table.component.html',
  styleUrls: ['./planification-table.component.scss']
})
export class PlanificationTableComponent implements OnInit {


  datosTabla = [
    {
    Aplicacion: 3,
    FechaPlanificada: '04-06-2020',
    Huerto: 'S Globe 2015',
    SectorHuerto: 'L1-L2',
    ObjetivoAplicacion: 'Nutrición',
    Producto: 'Sulfato de Mg',
    IngredienteActivo: 'Mg' ,
    Dosis: '2',
    UnidadMedida: 'Lt' ,
    Dilucion: '100',
    Volumen: '1000',
    },
    {
      Aplicacion: 3,
      FechaPlanificada: '04-06-2020',
      Huerto: 'S Globe 2015',
      SectorHuerto: 'L1-L2',
      ObjetivoAplicacion: 'Nutrición',
      Producto: 'Sulfato de Mg',
      IngredienteActivo: 'Mg' ,
      Dosis: '2',
      UnidadMedida: 'Lt' ,
      Dilucion: '100',
      Volumen: '1000',
      },
      {
        Aplicacion: 3,
        FechaPlanificada: '04-06-2020',
        Huerto: 'S Globe 2015',
        SectorHuerto: 'L1-L2',
        ObjetivoAplicacion: 'Nutrición',
        Producto: 'Sulfato de Mg',
        IngredienteActivo: 'Mg' ,
        Dosis: '2',
        UnidadMedida: 'Lt' ,
        Dilucion: '100',
        Volumen: '1000',
        },
        {
          Aplicacion: 3,
          FechaPlanificada: '04-06-2020',
          Huerto: 'S Globe 2015',
          SectorHuerto: 'L1-L2',
          ObjetivoAplicacion: 'Nutrición',
          Producto: 'Sulfato de Mg',
          IngredienteActivo: 'Mg' ,
          Dosis: '2',
          UnidadMedida: 'Lt' ,
          Dilucion: '100',
          Volumen: '1000',
          },
          {
            Aplicacion: 3,
            FechaPlanificada: '04-06-2020',
            Huerto: 'S Globe 2015',
            SectorHuerto: 'L1-L2',
            ObjetivoAplicacion: 'Nutrición',
            Producto: 'Sulfato de Mg',
            IngredienteActivo: 'Mg' ,
            Dosis: '2',
            UnidadMedida: 'Lt' ,
            Dilucion: '100',
            Volumen: '1000',
            },
            {
              Aplicacion: 3,
              FechaPlanificada: '04-06-2020',
              Huerto: 'S Globe 2015',
              SectorHuerto: 'L1-L2',
              ObjetivoAplicacion: 'Nutrición',
              Producto: 'Sulfato de Mg',
              IngredienteActivo: 'Mg' ,
              Dosis: '2',
              UnidadMedida: 'Lt' ,
              Dilucion: '100',
              Volumen: '1000',
              },
              {
                Aplicacion: 3,
                FechaPlanificada: '04-06-2020',
                Huerto: 'S Globe 2015',
                SectorHuerto: 'L1-L2',
                ObjetivoAplicacion: 'Nutrición',
                Producto: 'Sulfato de Mg',
                IngredienteActivo: 'Mg' ,
                Dosis: '2',
                UnidadMedida: 'Lt' ,
                Dilucion: '100',
                Volumen: '1000',
                },
                {
                  Aplicacion: 3,
                  FechaPlanificada: '04-06-2020',
                  Huerto: 'S Globe 2015',
                  SectorHuerto: 'L1-L2',
                  ObjetivoAplicacion: 'Nutrición',
                  Producto: 'Sulfato de Mg',
                  IngredienteActivo: 'Mg' ,
                  Dosis: '2',
                  UnidadMedida: 'Lt' ,
                  Dilucion: '100',
                  Volumen: '1000',
                  },
                  {
                    Aplicacion: 3,
                    FechaPlanificada: '04-06-2020',
                    Huerto: 'S Globe 2015',
                    SectorHuerto: 'L1-L2',
                    ObjetivoAplicacion: 'Nutrición',
                    Producto: 'Sulfato de Mg',
                    IngredienteActivo: 'Mg' ,
                    Dosis: '2',
                    UnidadMedida: 'Lt' ,
                    Dilucion: '100',
                    Volumen: '1000',
                    },
                    {
                      Aplicacion: 3,
                      FechaPlanificada: '04-06-2020',
                      Huerto: 'S Globe 2015',
                      SectorHuerto: 'L1-L2',
                      ObjetivoAplicacion: 'Nutrición',
                      Producto: 'Sulfato de Mg',
                      IngredienteActivo: 'Mg' ,
                      Dosis: '2',
                      UnidadMedida: 'Lt' ,
                      Dilucion: '100',
                      Volumen: '1000',
                      },
                      {
                        Aplicacion: 3,
                        FechaPlanificada: '04-06-2020',
                        Huerto: 'S Globe 2015',
                        SectorHuerto: 'L1-L2',
                        ObjetivoAplicacion: 'Nutrición',
                        Producto: 'Sulfato de Mg',
                        IngredienteActivo: 'Mg' ,
                        Dosis: '2',
                        UnidadMedida: 'Lt' ,
                        Dilucion: '100',
                        Volumen: '1000',
                        },
  ];

  constructor() { }

  ngOnInit(): void {
  }

}
